[package]
name = "baremetal-pi"
version = "0.1.0"
authors = ["Evan Brass <evan-brass@pm.me>"]
edition = "2018"

[dependencies]

[profile.dev]
panic = "abort"
lto = "thin"

[profile.release]
panic = "abort"
lto = "fat"