[package]
name = "baremetal-pi"
version = "0.1.0"
authors = ["Evan Brass <evan-brass@pm.me>"]
edition = "2018"

[dependencies]
raspi3_boot = { path = "raspi3_boot" }

[package.metadata.cargo-xbuild]
sysroot_path = "xbuild_sysroot"
