[package]
name = "baremetal-pi"
version = "0.1.0"
authors = ["Evan Brass <evan-brass@pm.me>"]
edition = "2018"

[dependencies]
panic-abort = "0.3.1"

[package.metadata.cargo-xbuild]
sysroot_path = "xbuild_sysroot"
